---
- name: Check MS SQL Server Health and Space Utilization
  hosts: 10.112.0.10
  gather_facts: no
  vars:
    sql_instance: "10.112.0.10"
    sql_user: "rajusql"  # Replace with your SQL Server username
    sql_password: "Raju@2002"  # Replace with your SQL Server password
  tasks:
    - name: Get Database Space Utilization
      win_shell: |
        Invoke-Sqlcmd -Query "
        SELECT DB_NAME(database_id) AS DatabaseName,
               (size * 8) / 1024 AS SizeMB
        FROM sys.master_files
        WHERE type = 0;" -ServerInstance "{{ sql_instance }}" -Username "{{ sql_user }}" -Password "{{ sql_password }}"
      register: db_space
      ignore_errors: yes

    - name: Get Database Health
      win_shell: |
        Invoke-Sqlcmd -Query "
        SELECT name, state_desc, recovery_model_desc 
        FROM sys.databases;" -ServerInstance "{{ sql_instance }}" -Username "{{ sql_user }}" -Password "{{ sql_password }}"
      register: db_health
      ignore_errors: yes

    - name: Check Deadlocks
      win_shell: |
        Invoke-Sqlcmd -Query "
        DBCC TRACEON(1222, -1);
        SELECT * FROM sys.dm_exec_requests WHERE blocking_session_id <> 0;" -ServerInstance "{{ sql_instance }}" -Username "{{ sql_user }}" -Password "{{ sql_password }}"
      register: deadlocks
      ignore_errors: yes
    
    - name: Get SQL Agent Job Activities
      win_shell: |
        Invoke-Sqlcmd -Query "
        SELECT job_id, name, enabled 
        FROM msdb.dbo.sysjobs;" -ServerInstance "{{ sql_instance }}" -Username "{{ sql_user }}" -Password "{{ sql_password }}"
      register: job_activities
      ignore_errors: yes

    - name: Show Database Space Utilization
      debug:
        msg: "{{ db_space.stdout_lines }}"

    - name: Show Database Health
      debug:
        msg: "{{ db_health.stdout_lines }}"

    - name: Show Deadlocks Information
      debug:
        msg: "{{ deadlocks.stdout_lines }}"

    - name: Show SQL Agent Job Activities
      debug:
        msg: "{{ job_activities.stdout_lines }}"
