---
- name: SQL Server Health Check and Maintenance
  hosts: 10.112.0.10
  gather_facts: no
  vars:
    sql_instance: "10.112.0.10"
    sql_user: "{{ sql_user }}"
    sql_password: "{{ sql_password }}"
  tasks:
    - name: Get Disk Space Utilization
      win_shell: |
        try {
          $disks = Get-WmiObject Win32_LogicalDisk | Select-Object DeviceID, VolumeName, Size, FreeSpace | ConvertTo-Json -Compress -Depth 2
          if (-not $disks) { Write-Output '[]' } else { Write-Output $disks }
        } catch {
          Write-Output '[{"Error": "Failed to retrieve disk info"}]'
        }
      register: disk_space
      ignore_errors: yes
    
    - name: Get Database Space Utilization
      win_shell: |
        try {
          $query = "SELECT DB_NAME(database_id) AS DatabaseName, SUM(size * 8) / 1024 AS SizeMB FROM sys.master_files GROUP BY database_id;"
          $result = Invoke-Sqlcmd -Query "$query" -ServerInstance "{{ sql_instance }}" -Username "{{ sql_user }}" -Password "{{ sql_password }}" -TrustServerCertificate | ConvertTo-Json -Compress -Depth 3
          if (-not $result) { Write-Output '[]' } else { Write-Output $result }
        } catch {
          Write-Output '[{"Error": "Failed to retrieve database space info"}]'
        }
      register: db_space
      ignore_errors: yes
    
    - name: Convert Outputs to JSON
      set_fact:
        disk_space_fact: "{{ disk_space.stdout | default('[]') | from_json }}"
        db_space_fact: "{{ db_space.stdout | default('[]') | from_json }}"
    
    - name: Ensure facts are lists
      set_fact:
        disk_space_fact: "{{ disk_space_fact if disk_space_fact is iterable else [] }}"
        db_space_fact: "{{ db_space_fact if db_space_fact is iterable else [] }}"
    
    - name: Display Formatted Results
      debug:
        msg: |
          💾 Disk Space:
          {% for item in disk_space_fact if item is mapping and 'DeviceID' in item and 'FreeSpace' in item %}
            - Volume: {{ item.DeviceID }} | Free Space: {{ (item.FreeSpace | int / 1073741824) | round(2) }} GB
          {% else %}
            - No valid disk space data available.
          {% endfor %}
          
          📊 Database Space Utilization:
          {% for item in db_space_fact if item is mapping and 'DatabaseName' in item and 'SizeMB' in item %}
            - {{ item.DatabaseName }}: {{ item.SizeMB }} MB
          {% else %}
            - No valid database space data available.
          {% endfor %}
