---
- name: Check MS SQL Server Health
  hosts: 10.112.0.10
  gather_facts: no
  vars:
    sql_instance: "10.112.0.10"  # Define the SQL Server instance here
  tasks:
    - name: Get Database Space Utilization
      win_shell: |
        Invoke-Sqlcmd -Query "
        SELECT DB_NAME(database_id) AS DatabaseName,
               (size * 8) / 1024 AS SizeMB
        FROM sys.master_files
        WHERE type = 0;" -ServerInstance "{{ sql_instance }}"
      register: db_space

    - name: Get Database Health
      win_shell: |
        Invoke-Sqlcmd -Query "
        SELECT name, state_desc, recovery_model_desc 
        FROM sys.databases;" -ServerInstance "{{ sql_instance }}"
      register: db_health

    - name: Check for Deadlocks
      win_shell: |
        Invoke-Sqlcmd -Query "
        SELECT COUNT(*) AS Deadlocks
        FROM sys.dm_tran_locks
        WHERE request_status = 'WAIT';" -ServerInstance "{{ sql_instance }}"
      register: deadlocks

    - name: Get SQL Agent Job Activities
      win_shell: |
        Invoke-Sqlcmd -Query "
        SELECT job_id, name, last_run_outcome, enabled 
        FROM msdb.dbo.sysjobs;" -ServerInstance "{{ sql_instance }}"
      register: job_activities

    - name: Display Results
      debug:
        msg:
          - "Database Space Utilization: {{ db_space.stdout }}"
          - "Database Health: {{ db_health.stdout }}"
          - "Deadlocks: {{ deadlocks.stdout }}"
          - "SQL Agent Job Activities: {{ job_activities.stdout }}"
