---
- name: MS SQL Server Monitoring
  hosts: all
  gather_facts: no
  vars:
    ansible_user: "raju"
    ansible_password: "Ascendion@9$"
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    sql_server: "20.102.105.60"
    sql_database: "master"
    sql_username: "rajusql"
    sql_password: "Raju@2002"

  tasks:
    - name: Check Database Space Utilization
      win_shell: |
        $query = @"
        SELECT DB_NAME(database_id) AS DatabaseName, SUM(size * 8) / 1024 AS TotalSizeMB
        FROM sys.master_files GROUP BY database_id;
        "@
        Invoke-Sqlcmd -Query $query -ServerInstance "{{ sql_server }}" -Username "{{ sql_username }}" -Password "{{ sql_password }}" -TrustServerCertificate Yes
      register: db_space_output

    - name: Display Database Space Utilization
      debug:
        msg: "{{ db_space_output.stdout_lines }}"

    - name: Check for Deadlocks
      win_shell: |
        $query = "SELECT * FROM sys.dm_tran_locks WHERE request_status = 'WAIT'"
        Invoke-Sqlcmd -Query $query -ServerInstance "{{ sql_server }}" -Username "{{ sql_username }}" -Password "{{ sql_password }}" -TrustServerCertificate Yes
      register: deadlocks_output

    - name: Display Deadlocks
      debug:
        msg: "{{ deadlocks_output.stdout_lines }}"

    - name: Check SQL Server Agent Job Activities
      win_shell: |
        $query = @"
        SELECT j.job_id, j.name, j.enabled, MAX(h.run_status) AS last_run_status
        FROM msdb.dbo.sysjobs j
        LEFT JOIN msdb.dbo.sysjobhistory h ON j.job_id = h.job_id
        WHERE h.step_id = 0
        GROUP BY j.job_id, j.name, j.enabled;
        "@
        Invoke-Sqlcmd -Query $query -ServerInstance "{{ sql_server }}" -Username "{{ sql_username }}" -Password "{{ sql_password }}" -TrustServerCertificate Yes
      register: job_activities_output

    - name: Display Job Activities
      debug:
        msg: "{{ job_activities_output.stdout_lines }}"

    - name: Execute Remote SQL Command via WinRM
      win_shell: |
        sqlcmd -S {{ sql_server }} -U {{ sql_username }} -P {{ sql_password }} -Q "SELECT @@VERSION"
      register: sql_version_output

    - name: Display SQL Server Version
      debug:
        msg: "{{ sql_version_output.stdout_lines }}"

    - name: Check Database Health
      win_shell: |
        $query = @"
        SELECT name AS DatabaseName, state_desc AS Status,
        (SELECT COUNT(*) FROM sys.dm_exec_requests) AS ActiveRequests,
        (SELECT COUNT(*) FROM sys.dm_exec_sessions WHERE is_user_process = 1) AS ActiveUserConnections,
        (SELECT COUNT(*) FROM sys.dm_os_waiting_tasks) AS PendingRequests,
        (SELECT COUNT(*) FROM sys.dm_os_performance_counters WHERE counter_name = 'Processor Queue Length') AS CPUQueueLength
        FROM sys.databases;
        "@
        Invoke-Sqlcmd -Query $query -ServerInstance "{{ sql_server }}" -Username "{{ sql_username }}" -Password "{{ sql_password }}" -TrustServerCertificate Yes
      register: db_health_output

    - name: Display Database Health
      debug:
        msg: "{{ db_health_output.stdout_lines }}"
